### ISSUE TITLE
Data Not Being Saved When Working With Inputmask

### ISSUE THREAD

**Issue by vkoves** [poteto/ember-changeset#197] opened 2017-07-31 18:01 UTC
I'm using [ember-inputmask](https://github.com/pzuraq/ember-inputmask) and am having trouble with ember-changeset not noticing changes on form fields. Why might this be, and can I remedy the situation?

I'm also using [ember-form-for](https://github.com/martndemus/ember-form-for) if that makes any difference, and have been able to prove that the input mask is causing the problem. However, if I read the value of the input masked field in with Javascript, it works fine, as shown here:

![screenshot from 2017-07-31 13-01-31](https://user-images.githubusercontent.com/3187531/28790935-64877f90-75f0-11e7-85c9-70a455e0ee4b.png)

**Comment by nucleartide** [comment] 2018-01-09 05:46
@vkoves Thanks for opening the issue. Since this issue is somewhat old, I'm going to close this.

If you're still interested, please open a new issue with an Ember Twiddle reproduction so it'll be easier to debug.

**Closed by nucleartide** 2018-01-09 05:46 UTC
