### ISSUE TITLE
content.save error not caught via promise-chaining

### ISSUE THREAD

**Issue by MuseofMoose** [poteto/ember-changeset#304] opened 2018-07-12 21:39 UTC
Version 1.5.0-beta.0

I have a block of code that is something like this:
```
changeset.save()
  .then(() => { /* ... */ })
  .catch((e) => { /* ... */ });
```

My ember-data entity was in an invalid state so when `changeset.save()` (and subsequently `content.save()`) was called, an error was thrown (as expected). The problem, however, was that the error was not caught by the `.catch()` and was directly dumped into the browser console. Wrapping changeset.save() in a try/catch block does catch the error and allow me to work with it (and it's my current work-around).

Given that the documentation for ember-changeset suggests promise chaining as a means of handling
errors, I would not expect to have to rely on a try catch block to handle the ember-data error.

If there's any other info you need, let me know. Thanks!

**Comment by brigham-hausman** [comment] 2018-07-19 00:31
Same problem here. Adding more fuel to the fire is the fact that the error thrown to the browser does not provide any useful details:
"Assertion Failed: [ember-deep-set] non-object passed in"
Is it possible to at least provide the broken property key?

**Comment by snewcomer** [comment] 2018-08-06 03:43
@MuseofMoose @jelhan So the promise returned by save is wrapped in `resolve` for non promise content.  

```
return savePromise.then((result) => {
  changeset.rollback();
  return resolve(result);
});
```

**Comment by snewcomer** [comment] 2018-08-06 04:07
@jelhan @MuseofMoose (sry accidentally closed) - So the resolve is there to protect from a value that is either a value or promise. 

Since `save` rejects, the Promise is in a rejected state, so it finds the closest handler, which is the `then`, without a `catch` clause.  It seems we want to rethrow in the middle of the chain...

```
return resolve(savePromise).then((result) => {
});
```

**Comment by urbany** [comment] 2018-08-06 09:16
I'm not sure it's ebcause of the wrapping resolve(), because:
```
> const p = new Ember.RSVP.Promise(function(){});
> Ember.RSVP.resolve(a) === p // is TRUE
```

So it should just return the underlying save promise.

**Comment by snewcomer** [comment] 2018-08-06 14:18
@MuseofMoose Was the ember-data invalid state caused by a failed xhr?  I failed to mention above that we already have a test for `failed proxy content` [here](https://github.com/poteto/ember-changeset/blob/master/tests/unit/changeset-test.js#L711).

What was the specific error?  Is this something easily reproducible?

**Comment by jelhan** [comment] 2018-08-06 15:10
> The thing with the reproduction above (which was super awesome +1) is that it would need to return reject('error is catchable') b/c we aren't inside a promise callback yet...

Totally missed the return. Updated the ember-twiddle and everything is working as expected: https://ember-twiddle.com/5e4c09e0469123592170cf38ef6414d2?openFiles=controllers.application.js%2C

**Comment by snewcomer** [comment] 2018-08-26 16:31
We might need a bit more information to tackle this one.  Will close this later in the week if we can't get further details.

**Comment by snewcomer** [comment] 2019-02-23 19:47
The original issue states the Ember data entity is already in an invalid state.  I think we need the shape of this already retired object so we can write a good test to solve this.

**Closed** 2020-06-15 15:06 UTC
