### ISSUE TITLE
Error: underlying object for changeset is missing

### ISSUE THREAD

**Issue by jfrux** [poteto/ember-changeset#149] opened 2017-02-23 20:52 UTC
I'm having trouble figuring out the exact way to use it.
I've followed some tutorials but I'm getting this error...

Anybody seen this before?

I'm running latest ember version and latest ember-changeset version.

**Comment by poteto** [comment] 2017-02-24 16:04
How are you using it?

**Comment by jonblack** [comment] 2017-03-08 09:14
I've seen this error when using the template helper and the model being passed in is `undefined`:

    {{my-component changeset=(changeset model)}}

I imagine the same error is also given if you do the same via javascript.

**Comment by marclundgren** [comment] 2017-07-13 00:34
I see this all the time in my test suite. I have no idea why it happens, and it causes false-negatives for my tests - worst of all, it's seemingly a race condition because it occurs non-deterministically.

**Comment by marclundgren** [comment] 2017-07-13 00:35
For me, when a test saves a new object, and transitions to a parent route, I see this error between the save and the transition.

**Comment by samharnack** [comment] 2017-09-02 15:50
I just ran into this error. For me, this was because I had the following model: 

```
{
  "filename": "file.jpg",
  "size": 0,
  "mimeType": "image/jpeg"
}
```

Internally, ember-changeset uses `isPresent` to ensure the model is present.
https://github.com/DockYard/ember-changeset/blob/master/addon/index.js#L56

The problem is `isPresent` eventually calls `isEmpty`. `isEmpty` uses `obj.size` to check for presence:
https://github.com/emberjs/ember.js/blob/v2.14.1/packages/ember-metal/lib/is_empty.js#L36

Which obviously/not so obviously fails because I have a size property on my model that is 0.

**Comment by tinyweasel** [comment] 2017-09-15 09:16
I'm also running into this error in an acceptance test for visiting a page with a few components that use a changeset. How do I integrate the changeset into the test to make it pass?

**Comment by aandresrafael** [comment] 2017-11-08 18:49
Hello I'm also running into this error as well in integration test for a component.  My component is like this.
form-component.js:
`import Ember from 'ember';
import AppReleaseValidations from '../validations/app-release';
import lookupValidator from 'ember-changeset-validations';
import Changeset from 'ember-changeset';

const { Component, get } = Ember;

export default Component.extend({
  init() {
    this._super(...arguments);
    let model = get(this, 'model');
    this.changeset = new Changeset(model, lookupValidator(AppReleaseValidations), AppReleaseValidations);
  }
});
`
form-component.hbs:
`     <form class="form">
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                {{validated-textbox-field
                  property="fiel1"
                  placeholder="Field 1"
                  changeset=changeset
                  validateProperty=(action validateProperty changeset "version")
                }}
              </div>
            </div>
            <div class="col-sm-6">
              <div class="form-group">
                {{validated-textbox-field
                  property="build"
                  placeholder="Build"
                  changeset=changeset
                  validateProperty=(action validateProperty changeset "build")
                }}
              </div>`
form-component-test.js:
`import { moduleForComponent, test } from 'ember-qunit';
import hbs from 'htmlbars-inline-precompile';


moduleForComponent('app-release-form', 'Integration | Component | app release form', {
  integration: true
});

test('it renders', function(assert) {

  // Set any properties with this.set('myProperty', 'value');
  // Handle any actions with this.on('myAction', function(val) { ... });
  this.render(hbs`{{app-release-form}}`);

  assert.equal(this.$().text().trim(), '');

});
`

Any idea how to solve this problem?

**Comment by JhonM** [comment] 2018-07-26 09:03
Hello, i'm also running into this error. Any updates on this issue?

**Comment by tinyweasel** [comment] 2018-07-26 20:12
That was my issue too, mocks weren't being properly loaded.

**Comment by snewcomer** [comment] 2019-01-08 04:08
closing for now!

**Closed by snewcomer** 2019-01-08 04:08 UTC
